*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVCA_METRICAS...................................*
FORM GET_DATA_ZVCA_METRICAS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTCA_METRICAS WHERE
(VIM_WHERETAB) .
    CLEAR ZVCA_METRICAS .
ZVCA_METRICAS-CLIENT =
ZTCA_METRICAS-CLIENT .
ZVCA_METRICAS-ESPEC =
ZTCA_METRICAS-ESPEC .
ZVCA_METRICAS-TIPO =
ZTCA_METRICAS-TIPO .
ZVCA_METRICAS-COMPLEX =
ZTCA_METRICAS-COMPLEX .
ZVCA_METRICAS-METRICA =
ZTCA_METRICAS-METRICA .
<VIM_TOTAL_STRUC> = ZVCA_METRICAS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVCA_METRICAS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVCA_METRICAS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVCA_METRICAS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_METRICAS WHERE
  ESPEC = ZVCA_METRICAS-ESPEC AND
  TIPO = ZVCA_METRICAS-TIPO AND
  COMPLEX = ZVCA_METRICAS-COMPLEX .
    IF SY-SUBRC = 0.
    DELETE ZTCA_METRICAS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_METRICAS WHERE
  ESPEC = ZVCA_METRICAS-ESPEC AND
  TIPO = ZVCA_METRICAS-TIPO AND
  COMPLEX = ZVCA_METRICAS-COMPLEX .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTCA_METRICAS.
    ENDIF.
ZTCA_METRICAS-CLIENT =
ZVCA_METRICAS-CLIENT .
ZTCA_METRICAS-ESPEC =
ZVCA_METRICAS-ESPEC .
ZTCA_METRICAS-TIPO =
ZVCA_METRICAS-TIPO .
ZTCA_METRICAS-COMPLEX =
ZVCA_METRICAS-COMPLEX .
ZTCA_METRICAS-METRICA =
ZVCA_METRICAS-METRICA .
    IF SY-SUBRC = 0.
    UPDATE ZTCA_METRICAS ##WARN_OK.
    ELSE.
    INSERT ZTCA_METRICAS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVCA_METRICAS-UPD_FLAG,
STATUS_ZVCA_METRICAS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVCA_METRICAS.
  SELECT SINGLE * FROM ZTCA_METRICAS WHERE
ESPEC = ZVCA_METRICAS-ESPEC AND
TIPO = ZVCA_METRICAS-TIPO AND
COMPLEX = ZVCA_METRICAS-COMPLEX .
ZVCA_METRICAS-CLIENT =
ZTCA_METRICAS-CLIENT .
ZVCA_METRICAS-ESPEC =
ZTCA_METRICAS-ESPEC .
ZVCA_METRICAS-TIPO =
ZTCA_METRICAS-TIPO .
ZVCA_METRICAS-COMPLEX =
ZTCA_METRICAS-COMPLEX .
ZVCA_METRICAS-METRICA =
ZTCA_METRICAS-METRICA .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVCA_METRICAS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVCA_METRICAS-ESPEC TO
ZTCA_METRICAS-ESPEC .
MOVE ZVCA_METRICAS-TIPO TO
ZTCA_METRICAS-TIPO .
MOVE ZVCA_METRICAS-COMPLEX TO
ZTCA_METRICAS-COMPLEX .
MOVE ZVCA_METRICAS-CLIENT TO
ZTCA_METRICAS-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTCA_METRICAS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTCA_METRICAS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTCA_METRICAS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
